

services:
  app:
    container_name: fastapi_app
#    image: .candycard:latest
    build:
      context: .
      dockerfile: Dockerfile  # Optional: specify if your Dockerfile is not named 'Dockerfile'

    command: uvicorn app:app --host 0.0.0.0 --port 8000
    volumes:
      - /app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/leitner
#      - PYTHONPATH=${PYTHONPATH}:/app/candycard

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: leitner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
